# Generated by Django 3.1.7 on 2021-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210310_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='images/', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='UserPorfilePic',
        ),
    ]
