# Generated by Django 3.1.7 on 2021-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210310_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='images/coverimage', upload_to='images/'),
        ),
    ]
