# Generated by Django 3.1.7 on 2021-04-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210406_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_cover',
        ),
    ]
