# Generated by Django 3.1.7 on 2021-04-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_billingaddress_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
