# Generated by Django 3.1.7 on 2021-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210409_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.CharField(default='T9U7TVNG', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
