# Generated by Django 3.1.7 on 2021-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210409_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='id',
            field=models.CharField(default='UFCHBO9W', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
