# Generated by Django 3.1.7 on 2021-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210409_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='id',
            field=models.CharField(default='3544BF', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
