# Generated by Django 3.1.7 on 2021-04-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210410_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='cancelStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.CharField(default='E24D13', editable=False, max_length=15, unique=True),
        ),
    ]
