# Generated by Django 3.1.7 on 2021-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210412_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.CharField(default='E030DD', editable=False, max_length=15, unique=True),
        ),
    ]
