# Generated by Django 3.1.7 on 2021-05-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210412_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='paid_unpaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.CharField(default='4B313F', editable=False, max_length=15, unique=True),
        ),
    ]
