# Generated by Django 3.1.7 on 2021-06-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210507_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.CharField(default='2D43F5', editable=False, max_length=15, unique=True),
        ),
    ]
